"""Markdown report exporter for ZeroTrace benchmark runs.

Generates human-readable .md summaries of completed inference runs.
No external dependencies — pure stdlib.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

_REPORTS_DIR = Path(__file__).parent / "data"
_REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def generate_report(
    results: Dict[str, Dict[str, Any]],
    model_name: str,
    run_timestamp: Optional[str] = None,
) -> str:
    """Build a Markdown report string from an inference run's results.

    Args:
        results:       Mapping of task_id → {reward, steps, error?}.
        model_name:    Name of the model used (e.g. "Qwen/Qwen2.5-72B-Instruct").
        run_timestamp: ISO timestamp string; defaults to now (UTC).

    Returns:
        Full Markdown report as a string.
    """
    if run_timestamp is None:
        run_timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    valid_rewards: List[float] = [
        r["reward"] for r in results.values() if "error" not in r
    ]
    mean_reward = sum(valid_rewards) / len(valid_rewards) if valid_rewards else 0.0
    total_tasks = len(results)
    passed_tasks = sum(
        1 for r in results.values() if r.get("reward", 0.0) >= 1.0
    )

    # --- header ---
    lines = [
        "# ZeroTrace Benchmark Report",
        "",
        f"**Model:** `{model_name}`  ",
        f"**Date:**  {run_timestamp}  ",
        f"**Tasks:** {total_tasks}  ",
        f"**Passed (reward=1.0):** {passed_tasks}/{total_tasks}  ",
        f"**Mean Reward:** `{mean_reward:.4f}`  ",
        "",
        "---",
        "",
        "## Per-Task Results",
        "",
        "| # | Task ID | Reward | Steps | Status |",
        "|---|---------|--------|-------|--------|",
    ]

    for idx, (task_id, r) in enumerate(results.items(), start=1):
        reward = r.get("reward", 0.0)
        steps = r.get("steps", 0)
        error = r.get("error", "")

        if error:
            status = f"❌ Error: {error[:60]}"
        elif reward >= 1.0:
            status = "✅ All tests passed"
        elif reward > 0.0:
            status = f"⚠️ Partial ({reward:.2f})"
        else:
            status = "❌ No tests passed"

        lines.append(f"| {idx} | `{task_id}` | `{reward:.4f}` | {steps} | {status} |")

    # --- validation section ---
    lines += [
        "",
        "---",
        "",
        "## Reward Validation",
        "",
    ]

    all_valid = True
    for task_id, r in results.items():
        reward = r.get("reward", 0.0)
        in_range = -1.0 <= reward <= 1.0
        if not in_range:
            all_valid = False
        symbol = "✅" if in_range else "❌"
        lines.append(f"- {symbol} `{task_id}`: reward = `{reward:.4f}`")

    lines += [
        "",
        f"**Validation:** {'✅ PASSED — all rewards in [-1.0, 1.0]' if all_valid else '❌ FAILED — rewards out of range'}",
        "",
        "---",
        "",
        "## Raw Results (JSON)",
        "",
        "```json",
        json.dumps(results, indent=2),
        "```",
        "",
        "_Generated by ZeroTrace_",
    ]

    return "\n".join(lines)


def save_report(
    results: Dict[str, Dict[str, Any]],
    model_name: str,
) -> Path:
    """Generate and persist a report to disk.

    Args:
        results:    Mapping of task_id → result dict.
        model_name: Model name used for the run.

    Returns:
        Path to the saved .md file.
    """
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    safe_model = model_name.replace("/", "_").replace(" ", "_")[:40]
    filename = f"report_{safe_model}_{ts}.md"
    path = _REPORTS_DIR / filename

    content = generate_report(results, model_name)
    path.write_text(content, encoding="utf-8")
    return path
